### ISSUE TITLE
Object #<Object> has no method 'loadUtils'

### ISSUE THREAD

**Issue by raza2022** [bendetat/nancy-gulp-bower-angular-learnings#1]
i followed your way but it tells on running 
Object #<Object> has no method 'loadUtils'

**Comment by becdetat** [comment]
I'm guessing it fails around here:

```
log: require('gulp-load-plugins')()
    .loadUtils(['log'])
    .log
```

Is the `gulp-load-plugins` present in `node_modules/gulp-load-plugins`? If not you may need to `npm install --save-dev gulp-load-plugins` first. My [blog post](http://bendetat.com/hello-world-its-gulp.html) goes through this. Let me know if you have any more problems.

**Comment by raza2022** [comment]
ok i work around this by my customized method
Thanks....

**Comment by becdetat** [comment]
No worries, let me know if I should update something to help the next person ;-)
